// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecondDimensionWatcherReDive.Models;

#nullable disable

namespace SecondDimensionWatcherReDive.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260827125735_AddSubscriptionAutomation")]
    partial class AddSubscriptionAutomation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.Animation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<string>("TmdbId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Animations");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnimationGroups");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalDownloadInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AiRetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AnimationId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutomationDisposition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AutomationExplanationJson")
                        .HasColumnType("text");

                    b.Property<byte[]>("CachedDownloadData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DownloadEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DownloadStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Episode")
                        .HasColumnType("integer");

                    b.Property<string>("FileStore")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAiProcessed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDownloadFinished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDownloadTracked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("PublishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ReleaseSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("Season")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceFeedId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorePath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimationId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SourceFeedId");

                    b.ToTable("AnimationInfo");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.BangumiSubgroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MikanSubgroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonBangumiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeasonBangumiId", "MikanSubgroupId")
                        .IsUnique();

                    b.ToTable("BangumiSubgroups");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatConversations");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileStore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimationInfoId");

                    b.HasIndex("VirtualPath")
                        .IsUnique();

                    b.ToTable("FileMappings");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileNameRegexRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("AnimationId", "CreatedAt");

                    b.HasIndex("AnimationId", "Pattern")
                        .IsUnique();

                    b.ToTable("FileNameRegexRules");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.MigrationMarker", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("MigrationMarkers");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.SeasonBangumi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MikanId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MikanId")
                        .IsUnique();

                    b.ToTable("SeasonBangumis");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.SubscriptionAutomationPolicy", b =>
                {
                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Codecs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("ExcludedKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long?>("MaxSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<string[]>("Resolutions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("SubtitleGroups")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeedId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SubscriptionAutomationPolicies");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.WebDavToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("WebDavTokens");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationInfo", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.Animation", "Animation")
                        .WithMany()
                        .HasForeignKey("AnimationId");

                    b.HasOne("SecondDimensionWatcherReDive.Models.AnimationGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SecondDimensionWatcherReDive.Models.Feed", null)
                        .WithMany()
                        .HasForeignKey("SourceFeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Animation");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.BangumiSubgroup", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.SeasonBangumi", "SeasonBangumi")
                        .WithMany("Subgroups")
                        .HasForeignKey("SeasonBangumiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeasonBangumi");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ChatMessage", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.ChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileNameRegexRule", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.Animation", null)
                        .WithMany()
                        .HasForeignKey("AnimationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.SubscriptionAutomationPolicy", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.Feed", "Feed")
                        .WithOne()
                        .HasForeignKey("SecondDimensionWatcherReDive.Models.SubscriptionAutomationPolicy", "FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.SeasonBangumi", b =>
                {
                    b.Navigation("Subgroups");
                });
#pragma warning restore 612, 618
        }
    }
}
