// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecondDimensionWatcherReDive.Models;

#nullable disable

namespace SecondDimensionWatcherReDive.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260831090146_AddReleaseUpgradeSubmissionRecovery")]
    partial class AddReleaseUpgradeSubmissionRecovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.Animation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<string>("TmdbId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Animations");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationCatalogEntry", b =>
                {
                    b.Property<Guid>("AnimationId")
                        .HasColumnType("uuid");

                    b.Property<int>("AutomationAttentionCount")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LatestPublishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<int>("ReleaseCount")
                        .HasColumnType("integer");

                    b.Property<string>("TmdbId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnimationId");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.HasIndex("LatestPublishTime", "TmdbId")
                        .IsDescending();

                    b.ToTable("AnimationCatalogEntries", t =>
                        {
                            t.HasCheckConstraint("CK_AnimationCatalogEntries_Counts", "\"EpisodeCount\" >= 0 AND \"ReleaseCount\" > 0 AND \"AutomationAttentionCount\" >= 0");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationCatalogState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AnimationCatalogStates", t =>
                        {
                            t.HasCheckConstraint("CK_AnimationCatalogStates_Revision_Positive", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_AnimationCatalogStates_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AnimationGroups");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalDownloadInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AiRetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AnimationId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutomationDisposition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AutomationExplanationJson")
                        .HasColumnType("text");

                    b.Property<byte[]>("CachedDownloadData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("CurrentMetadataReviewOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DownloadAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DownloadSubmissionLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DownloadSubmissionLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DownloadCancellationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DownloadCancellationLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DownloadCancellationLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DownloadCancellationRemoveFile")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("DownloadEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DownloadStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnclosureId")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("Episode")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedEpisodeCount")
                        .HasColumnType("integer");

                    b.Property<string>("FeedItemGuid")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("FileStore")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActiveRelease")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAiProcessed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDownloadFinished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDownloadTracked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRetiredRelease")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MediaLibraryMissingSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MediaLibrarySourceId")
                        .HasColumnType("uuid");

                    b.Property<double?>("MetadataConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("MetadataLastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("MetadataReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetadataStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PublishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReleaseCodec")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReleaseIdentity")
                        .HasMaxLength(192)
                        .HasColumnType("character varying(192)");

                    b.PrimitiveCollection<string[]>("ReleaseLanguages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ReleaseResolution")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ReleaseScore")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseScoreReasonsJson")
                        .HasColumnType("text");

                    b.Property<long?>("ReleaseSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ReleaseSubtitleGroup")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Season")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceFeedId")
                        .HasColumnType("uuid");

                    b.Property<long>("StateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StorePath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TorrentInfoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentMetadataReviewOperationId")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("MediaLibrarySourceId");

                    b.HasIndex("ReleaseCodec");

                    b.HasIndex("ReleaseIdentity")
                        .IsUnique()
                        .HasDatabaseName("UX_AnimationInfo_ReleaseIdentity")
                        .HasFilter("\"ReleaseIdentity\" IS NOT NULL");

                    b.HasIndex("ReleaseResolution");

                    b.HasIndex("ReleaseSubtitleGroup");

                    b.HasIndex("SourceFeedId");

                    b.HasIndex("AutomationDisposition", "PublishTime");

                    b.HasIndex("FileStore", "StorePath")
                        .IsUnique()
                        .HasFilter("\"DownloadType\" = 'http://schemas.hcgstudio.com/ws/2023/06/sdw/downloadtype/media-library-import'");

                    b.HasIndex("MetadataStatus", "PublishTime");

                    b.HasIndex("AnimationId", "PublishTime", "Id");

                    b.HasIndex("AnimationId", "Season", "Episode")
                        .IsUnique()
                        .HasDatabaseName("UX_AnimationInfo_ActiveEpisodeRelease")
                        .HasFilter("\"IsActiveRelease\" = TRUE AND \"AnimationId\" IS NOT NULL AND \"Season\" IS NOT NULL AND \"Episode\" IS NOT NULL");

                    b.HasIndex("DownloadType", "IsDownloadFinished", "IsDownloadTracked");

                    b.HasIndex("MediaLibraryMissingSince", "PublishTime", "Id");

                    b.HasIndex("Season", "Episode", "ReleaseScore");

                    b.ToTable("AnimationInfo", t =>
                        {
                            t.HasCheckConstraint("CK_AnimationInfo_ExpectedEpisodeCount_Positive", "\"ExpectedEpisodeCount\" IS NULL OR \"ExpectedEpisodeCount\" > 0");

                            t.HasCheckConstraint("CK_AnimationInfo_MetadataConfidence_Range", "\"MetadataConfidence\" IS NULL OR (\"MetadataConfidence\" >= 0 AND \"MetadataConfidence\" <= 1)");

                            t.HasCheckConstraint("CK_AnimationInfo_ReleaseScore_NonNegative", "\"ReleaseScore\" >= 0");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ProtectedSecrets")
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings", t =>
                        {
                            t.HasCheckConstraint("CK_ApplicationSettings_Revision_Positive", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_ApplicationSettings_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AuthenticationState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationStates", t =>
                        {
                            t.HasCheckConstraint("CK_AuthenticationStates_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.BangumiSubgroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MikanSubgroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonBangumiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeasonBangumiId", "MikanSubgroupId")
                        .IsUnique();

                    b.ToTable("BangumiSubgroups");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChatConversations");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("text");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileStore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimationInfoId");

                    b.HasIndex("VirtualPath")
                        .IsUnique();

                    b.ToTable("FileMappings", t =>
                        {
                            t.HasCheckConstraint("CK_FileMappings_VirtualPath_Canonical", "\"VirtualPath\" ~ '^/[^/]+(?:/[^/]+)*$' AND \"VirtualPath\" !~ '(^|/)\\.\\.?($|/)'");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileNameRegexRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("AnimationId", "CreatedAt");

                    b.HasIndex("AnimationId", "Pattern")
                        .IsUnique();

                    b.ToTable("FileNameRegexRules");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileSystemDirectoryState", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.HasKey("Path");

                    b.ToTable("FileSystemDirectoryStates", t =>
                        {
                            t.HasCheckConstraint("CK_FileSystemDirectoryStates_Generation_Positive", "\"Generation\" > 0");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileSystemEntry", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<long>("Cookie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('sdw_file_system_entry_cookie_seq')");

                    b.Property<int>("DescendantFileCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("FileMappingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Path");

                    b.HasIndex("Cookie")
                        .IsUnique();

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.HasIndex("FileMappingId")
                        .IsUnique()
                        .HasFilter("\"FileMappingId\" IS NOT NULL");

                    b.HasIndex("ParentPath", "Cookie");

                    b.HasIndex("ParentPath", "IsDirectory", "Name")
                        .IsDescending(false, true, false);

                    b.ToTable("FileSystemEntries", t =>
                        {
                            t.HasCheckConstraint("CK_FileSystemEntries_NodeShape", "(\"IsDirectory\" AND \"FileMappingId\" IS NULL AND \"DescendantFileCount\" > 0) OR (NOT \"IsDirectory\" AND \"FileMappingId\" IS NOT NULL AND \"DescendantFileCount\" = 1)");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTimeOffset?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRetryError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Occurrence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("ResolvedAt", "Type", "UpdatedAt");

                    b.ToTable("Incidents", t =>
                        {
                            t.HasCheckConstraint("CK_Incidents_Occurrence_Positive", "\"Occurrence\" > 0");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.MediaLibrarySource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMonitoring")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("LastImportedCount")
                        .HasColumnType("integer");

                    b.Property<int>("LastRemovedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastScanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastSkippedCount")
                        .HasColumnType("integer");

                    b.Property<int>("LastUpdatedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("MediaLibrarySources");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.MetadataReviewMappingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileStore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Kind", "VirtualPath")
                        .IsUnique();

                    b.ToTable("MetadataReviewMappingSnapshots", t =>
                        {
                            t.HasCheckConstraint("CK_MetadataReviewMappingSnapshots_VirtualPath_Canonical", "\"VirtualPath\" ~ '^/[^/]+(?:/[^/]+)*$' AND \"VirtualPath\" !~ '(^|/)\\.\\.?($|/)'");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.MetadataReviewOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("AppliedVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseFileStore")
                        .HasColumnType("text");

                    b.Property<bool>("BaseIsDownloadFinished")
                        .HasColumnType("boolean");

                    b.Property<string>("BaseStorePath")
                        .HasColumnType("text");

                    b.Property<long>("BaseVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PreviousAiRetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousAnimationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PreviousConfidence")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("PreviousCurrentOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousDescription")
                        .HasColumnType("text");

                    b.Property<int?>("PreviousEpisode")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("PreviousIsAiProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousLastError")
                        .HasColumnType("text");

                    b.Property<int?>("PreviousMetadataStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PreviousReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PreviousSeason")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedAnimationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedAnimationOriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedAnimationPosterPath")
                        .HasColumnType("text");

                    b.Property<string>("ProposedAnimationTmdbId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProposedEpisode")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedGroupName")
                        .HasColumnType("text");

                    b.Property<int?>("ProposedSeason")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UndoneAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimationInfoId", "AppliedVersion")
                        .IsUnique();

                    b.HasIndex("AnimationInfoId", "State");

                    b.HasIndex("State", "ExpiresAt");

                    b.ToTable("MetadataReviewOperations", t =>
                        {
                            t.HasCheckConstraint("CK_MetadataReviewOperations_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.MigrationExecutionState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Checkpoint")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Key", "Version");

                    b.ToTable("MigrationMarkers", null, t =>
                        {
                            t.HasCheckConstraint("CK_MigrationMarkers_AttemptCount_NonNegative", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_MigrationMarkers_Status_Range", "\"Status\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_MigrationMarkers_Version_Positive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.NotificationOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DeepLink")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid?>("WebPushSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("WebPushSubscriptionId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("NotificationOutboxMessages");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.PlaybackCatalogState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("PlaybackCatalogStates", t =>
                        {
                            t.HasCheckConstraint("CK_PlaybackCatalogStates_Revision_Positive", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.PlaybackPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AudioLanguage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AudioTrackLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("AutoPlayNext")
                        .HasColumnType("boolean");

                    b.Property<string>("SubtitleLanguage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SubtitleTrackLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("PlaybackPreferences");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.PlaybackProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationInfoId")
                        .HasColumnType("uuid");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("boolean");

                    b.Property<double>("PositionSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimationInfoId");

                    b.HasIndex("UserId", "AnimationInfoId", "VirtualPath")
                        .IsUnique();

                    b.HasIndex("UserId", "IsWatched", "UpdatedAt");

                    b.ToTable("PlaybackProgresses", t =>
                        {
                            t.HasCheckConstraint("CK_PlaybackProgresses_Duration_NonNegative", "\"DurationSeconds\" >= 0");

                            t.HasCheckConstraint("CK_PlaybackProgresses_Position_NonNegative", "\"PositionSeconds\" >= 0");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ReleaseUpgradeMappingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileStore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginalMappingId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Kind", "OriginalMappingId")
                        .IsUnique();

                    b.ToTable("ReleaseUpgradeMappingSnapshots", t =>
                        {
                            t.HasCheckConstraint("CK_ReleaseUpgradeMappingSnapshots_VirtualPath_Canonical", "\"VirtualPath\" ~ '^/[^/]+(?:/[^/]+)*$' AND \"VirtualPath\" !~ '(^|/)\\.\\.?($|/)'");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ReleaseUpgradeOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CandidateReleaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("CandidateScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentReleaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentScore")
                        .HasColumnType("integer");

                    b.Property<bool>("DownloadCancellationRemoveFile")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("DownloadPreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DownloadSubmissionLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DownloadSubmissionLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DownloadSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("RollbackUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateReleaseId")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Failed'");

                    b.HasIndex("CurrentReleaseId")
                        .IsUnique()
                        .HasDatabaseName("UX_ReleaseUpgradeOperations_ActiveCurrentRelease")
                        .HasFilter("\"Status\" IN ('Downloading', 'Verifying', 'Applied')");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ReleaseUpgradeOperations", t =>
                        {
                            t.HasCheckConstraint("CK_ReleaseUpgradeOperations_ScoreIncrease", "\"CandidateScore\" > \"CurrentScore\"");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.SeasonBangumi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MikanId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MikanId")
                        .IsUnique();

                    b.ToTable("SeasonBangumis");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.StagedFileMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimationInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileStore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("AnimationInfoId", "VirtualPath")
                        .IsUnique();

                    b.ToTable("StagedFileMappings", t =>
                        {
                            t.HasCheckConstraint("CK_StagedFileMappings_VirtualPath_Canonical", "\"VirtualPath\" ~ '^/[^/]+(?:/[^/]+)*$' AND \"VirtualPath\" !~ '(^|/)\\.\\.?($|/)'");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.SubscriptionAutomationPolicy", b =>
                {
                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Codecs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableVersionUpgrade")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("ExcludedKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long?>("MaxSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MinimumUpgradeScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(25);

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<string[]>("Resolutions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("SubtitleGroups")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpgradeRollbackHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(72);

                    b.HasKey("FeedId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SubscriptionAutomationPolicies", t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionAutomationPolicies_MinimumUpgradeScore", "\"MinimumUpgradeScore\" >= 1 AND \"MinimumUpgradeScore\" <= 1000");

                            t.HasCheckConstraint("CK_SubscriptionAutomationPolicies_UpgradeRollbackHours", "\"UpgradeRollbackHours\" >= 1 AND \"UpgradeRollbackHours\" <= 720");
                        });
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.TodoItemState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("TodoItemStates");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.WebDavToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("WebDavTokens");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.WebPushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedAuth")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ProtectedEndpoint")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("ProtectedP256Dh")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EndpointHash")
                        .IsUnique();

                    b.ToTable("WebPushSubscriptions");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationCatalogEntry", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.Animation", "Animation")
                        .WithOne()
                        .HasForeignKey("SecondDimensionWatcherReDive.Models.AnimationCatalogEntry", "AnimationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animation");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.AnimationInfo", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.Animation", "Animation")
                        .WithMany()
                        .HasForeignKey("AnimationId");

                    b.HasOne("SecondDimensionWatcherReDive.Models.AnimationGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SecondDimensionWatcherReDive.Models.MediaLibrarySource", null)
                        .WithMany()
                        .HasForeignKey("MediaLibrarySourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SecondDimensionWatcherReDive.Models.Feed", null)
                        .WithMany()
                        .HasForeignKey("SourceFeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Animation");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.BangumiSubgroup", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.SeasonBangumi", "SeasonBangumi")
                        .WithMany("Subgroups")
                        .HasForeignKey("SeasonBangumiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeasonBangumi");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ChatMessage", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.ChatConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileNameRegexRule", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.Animation", null)
                        .WithMany()
                        .HasForeignKey("AnimationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.FileSystemEntry", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.FileMapping", "FileMapping")
                        .WithOne()
                        .HasForeignKey("SecondDimensionWatcherReDive.Models.FileSystemEntry", "FileMappingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FileMapping");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.MetadataReviewMappingSnapshot", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.MetadataReviewOperation", "Operation")
                        .WithMany("MappingSnapshots")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.MetadataReviewOperation", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.AnimationInfo", "AnimationInfo")
                        .WithMany()
                        .HasForeignKey("AnimationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimationInfo");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.PlaybackProgress", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.AnimationInfo", "AnimationInfo")
                        .WithMany()
                        .HasForeignKey("AnimationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimationInfo");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ReleaseUpgradeMappingSnapshot", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.ReleaseUpgradeOperation", "Operation")
                        .WithMany("MappingSnapshots")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ReleaseUpgradeOperation", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.AnimationInfo", "CandidateRelease")
                        .WithMany()
                        .HasForeignKey("CandidateReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SecondDimensionWatcherReDive.Models.AnimationInfo", "CurrentRelease")
                        .WithMany()
                        .HasForeignKey("CurrentReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateRelease");

                    b.Navigation("CurrentRelease");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.StagedFileMapping", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.AnimationInfo", null)
                        .WithMany()
                        .HasForeignKey("AnimationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.SubscriptionAutomationPolicy", b =>
                {
                    b.HasOne("SecondDimensionWatcherReDive.Models.Feed", "Feed")
                        .WithOne()
                        .HasForeignKey("SecondDimensionWatcherReDive.Models.SubscriptionAutomationPolicy", "FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.MetadataReviewOperation", b =>
                {
                    b.Navigation("MappingSnapshots");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.ReleaseUpgradeOperation", b =>
                {
                    b.Navigation("MappingSnapshots");
                });

            modelBuilder.Entity("SecondDimensionWatcherReDive.Models.SeasonBangumi", b =>
                {
                    b.Navigation("Subgroups");
                });
#pragma warning restore 612, 618
        }
    }
}
