using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SecondDimensionWatcherReDive.Analyzers;

[Generator]
public sealed class ConfigMigrationGenerator : IIncrementalGenerator
{
    private const string MigrationInterfaceName =
        "SecondDimensionWatcherReDive.Framework.ConfigurationMigration.IConfigMigration";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var migrations = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                transform: static (syntaxContext, cancellationToken) =>
                {
                    var symbol = syntaxContext.SemanticModel.GetDeclaredSymbol(
                        (TypeDeclarationSyntax)syntaxContext.Node, cancellationToken) as INamedTypeSymbol;
                    if (symbol is null || symbol.TypeKind == TypeKind.Interface)
                        return null;

                    var migrationInterface = syntaxContext.SemanticModel.Compilation
                        .GetTypeByMetadataName(MigrationInterfaceName);
                    return migrationInterface is not null && symbol.AllInterfaces.Any(implemented =>
                        SymbolEqualityComparer.Default.Equals(implemented, migrationInterface))
                        ? symbol
                        : null;
                })
            .Where(static symbol => symbol is not null)
            .Collect();

        context.RegisterSourceOutput(migrations,
            static (sourceContext, symbols) => Generate(sourceContext, symbols));
    }

    private static void Generate(
        SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol?> migrationSymbols)
    {
        // The analyzer is shared with AI tool projects, which must not emit another registry.
        if (migrationSymbols.IsEmpty)
            return;

        var migrations = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var symbol in migrationSymbols)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            if (symbol is not null)
                migrations.Add(symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace SecondDimensionWatcherReDive.ConfigMigration;");
        source.AppendLine();
        source.AppendLine("public static class GeneratedConfigMigrations");
        source.AppendLine("{");
        source.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<");
        source.Append("        global::");
        source.Append(MigrationInterfaceName);
        source.AppendLine("> Create() =>");
        source.AppendLine("    [");

        foreach (var migration in migrations)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            source.Append("        new ");
            source.Append(migration);
            source.AppendLine("(),");
        }

        source.AppendLine("    ];");
        source.AppendLine("}");
        context.AddSource("GeneratedConfigMigrations.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
