using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SecondDimensionWatcherReDive.Analyzers;

[Generator]
public sealed class ToolGenerator : IIncrementalGenerator
{
    private const string ToolAttributeMetadataName = "SecondDimensionWatcherReDive.Framework.Attributes.ToolAttribute`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var toolClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ToolAttributeMetadataName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetToolInfo(ctx, ct))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(toolClasses, static (spc, info) => Execute(spc, info!.Value));
    }

    private static ToolInfo? GetToolInfo(GeneratorAttributeSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var classSymbol = (INamedTypeSymbol)context.TargetSymbol;

        // Validate partial
        var classDecl = (ClassDeclarationSyntax)context.TargetNode;
        var isPartial = false;
        foreach (var modifier in classDecl.Modifiers)
        {
            if (modifier.Text == "partial")
            {
                isPartial = true;
                break;
            }
        }

        if (!isPartial)
            return null;

        // Get the attribute data
        var attributeData = context.Attributes[0];
        var attributeClass = attributeData.AttributeClass;
        if (attributeClass is null || !attributeClass.IsGenericType || attributeClass.TypeArguments.Length != 1)
            return null;

        var paramType = attributeClass.TypeArguments[0];
        var paramTypeFqn = paramType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Get constructor arguments: (string name, string description, ToolRiskLevel riskLevel)
        if (attributeData.ConstructorArguments.Length < 3)
            return null;

        var toolName = attributeData.ConstructorArguments[0].Value as string;
        var toolDescription = attributeData.ConstructorArguments[1].Value as string;
        var riskLevel = attributeData.ConstructorArguments[2].Value as int?;
        if (toolName is null || toolDescription is null || riskLevel is null)
            return null;

        // Validate ExecuteCoreAsync method exists
        var hasExecuteCore = false;
        foreach (var member in classSymbol.GetMembers())
        {
            if (member is IMethodSymbol method
                && method.Name == "ExecuteCoreAsync"
                && method.Parameters.Length == 2
                && SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, paramType)
                && method.Parameters[1].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                   "global::System.Threading.CancellationToken")
            {
                hasExecuteCore = true;
                break;
            }
        }

        if (!hasExecuteCore)
            return null;

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        return new ToolInfo
        {
            Namespace = namespaceName,
            ClassName = classSymbol.Name,
            ParamTypeFqn = paramTypeFqn,
            ToolName = toolName,
            ToolDescription = toolDescription,
            RiskLevel = riskLevel.Value
        };
    }

    private static void Execute(SourceProductionContext context, ToolInfo info)
    {
        var escapedName = EscapeStringLiteral(info.ToolName);
        var escapedDescription = EscapeStringLiteral(info.ToolDescription);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.Append("namespace ");
            sb.Append(info.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ");
        sb.AppendLine(info.ClassName);
        sb.AppendLine("{");

        // Generate static Definition property
        sb.AppendLine("    public static global::SecondDimensionWatcherReDive.Framework.AI.ToolDefinition Definition { get; } =");
        sb.Append("        global::SecondDimensionWatcherReDive.Framework.AI.ToolDefinition.Create<");
        sb.Append(info.ParamTypeFqn);
        sb.AppendLine(">(");
        sb.Append("            \"");
        sb.Append(escapedName);
        sb.Append("\", \"");
        sb.Append(escapedDescription);
        sb.AppendLine("\",");
        sb.Append("            (global::SecondDimensionWatcherReDive.Framework.AI.ToolRiskLevel)");
        sb.Append(info.RiskLevel);
        sb.AppendLine(");");
        sb.AppendLine();

        // Generate ExecuteAsync method — param deserialization only, no result serialization
        sb.AppendLine("    public async global::System.Threading.Tasks.Task<global::SecondDimensionWatcherReDive.Framework.AI.IToolResult> ExecuteAsync(");
        sb.AppendLine("        global::System.Text.Json.JsonElement arguments,");
        sb.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.Append("        var param = global::System.Text.Json.JsonSerializer.Deserialize<");
        sb.Append(info.ParamTypeFqn);
        sb.AppendLine(">(");
        sb.AppendLine("            arguments,");
        sb.AppendLine("            global::SecondDimensionWatcherReDive.AI.Models.ToolJsonOptions.Options);");
        sb.AppendLine("        if (param is null)");
        sb.Append("            return new global::SecondDimensionWatcherReDive.AI.Models.ToolFailureResult(\"Failed to deserialize parameters for tool '");
        sb.Append(escapedName);
        sb.AppendLine("'\");");
        sb.AppendLine("        return await ExecuteCoreAsync(param, cancellationToken);");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        var hintName = info.Namespace is not null
            ? $"{info.Namespace}.{info.ClassName}.g.cs"
            : $"{info.ClassName}.g.cs";

        context.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r");
    }

    private struct ToolInfo
    {
        public string? Namespace;
        public string ClassName;
        public string ParamTypeFqn;
        public string ToolName;
        public string ToolDescription;
        public int RiskLevel;
    }
}
