<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>2D7A9485-A39A-4E36-9857-8DE90A0DA63A</UserSecretsId>
        <ContainerRegistry>ghcr.io</ContainerRegistry>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="8.0.2"/>
        <PackageReference Include="Aspire.Hosting.NodeJs" Version="8.0.2" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="8.0.2" />
        <PackageReference Include="Nall.Aspire.Hosting.DependsOn.All" Version="1.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SecondDimensionWatcherReDive.Gateway\SecondDimensionWatcherReDive.Gateway.csproj" />
      <ProjectReference Include="..\SecondDimensionWatcherReDive\SecondDimensionWatcherReDive.csproj" />
    </ItemGroup>

</Project>
