<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>0e827b46-7c5a-4230-9e45-d9abf65902aa</UserSecretsId>
        <AssemblyVersion>2.0.0</AssemblyVersion>
        <FileVersion>2.0.0</FileVersion>
        <ContainerRegistry>ghcr.io</ContainerRegistry>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspSpaService" Version="1.0.6" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
        <PackageReference Include="BencodeNET" Version="5.0.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="Mapster" Version="10.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="10.0.5" />
        <PackageReference Include="Microsoft.ClearScript.Complete" Version="7.5.0" />
        <PackageReference Include="Microsoft.ClearScript.Core" Version="7.5.0" />
        <PackageReference Include="Microsoft.ClearScript.V8" Version="7.5.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
        <PackageReference Include="System.Linq.Async" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SecondDimensionWatcherReDive.Framework\SecondDimensionWatcherReDive.Framework.csproj" />
      <ProjectReference Include="..\Plugins\SecondDimensionWatcherReDive.Inference.AI\SecondDimensionWatcherReDive.Inference.AI.csproj" />
      <ProjectReference Include="..\Plugins\SecondDimensionWatcherReDive.Plugin.FileRenamer\SecondDimensionWatcherReDive.Plugin.FileRenamer.csproj" />
    </ItemGroup>
</Project>