namespace SecondDimensionWatcherReDive.Framework.DataRepository;

public sealed record AnimationInfo(
    Guid Id,
    string Title,
    string Description,
    DateTimeOffset PublishTime,
    string DownloadUrl,
    string DownloadType,
    byte[] CachedDownloadData,
    string AdditionalDownloadInfo,
    bool IsDownloadTracked,
    DateTimeOffset DownloadStartTime,
    DateTimeOffset DownloadEndTime,
    bool IsDownloadFinished,
    string? FileStore,
    string? StorePath,
    int? Season,
    int? Episode,
    AnimationGroup? Group,
    Animation? Animation,
    bool IsAiProcessed,
    int AiRetryCount,
    Guid? SourceFeedId = null,
    long? ReleaseSizeBytes = null,
    SubscriptionAutomationDisposition? AutomationDisposition = null,
    string? AutomationExplanationJson = null,
    MetadataReviewStatus MetadataStatus = MetadataReviewStatus.Pending,
    double? MetadataConfidence = null,
    string? MetadataLastError = null,
    DateTimeOffset? MetadataReviewedAt = null,
    long StateVersion = 0,
    Guid? CurrentMetadataReviewOperationId = null,
    Guid? DownloadAttemptId = null,
    Guid? DownloadCancellationId = null,
    Guid? MediaLibrarySourceId = null,
    DateTimeOffset? MediaLibraryMissingSince = null,
    string? ReleaseIdentity = null,
    string? FeedItemGuid = null,
    string? EnclosureId = null,
    string? TorrentInfoHash = null,
    string? ReleaseSubtitleGroup = null,
    string? ReleaseResolution = null,
    string? ReleaseCodec = null,
    IReadOnlyList<string>? ReleaseLanguages = null,
    int ReleaseScore = 0,
    string? ReleaseScoreReasonsJson = null,
    int? ExpectedEpisodeCount = null,
    DateTimeOffset? IngestedAt = null,
    bool IsActiveRelease = true);
