/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx,html}"],
  theme: {
    extend: {
      colors: {
        canvas: "var(--theme-canvas)",
        surface: "var(--theme-surface)",
        tint: "var(--theme-tint)",
        "surface-muted": "var(--theme-surface-muted)",
        brand: "var(--theme-brand)",
        accent: "var(--theme-accent)",
        "on-brand": "var(--theme-on-brand)",
        foreground: "var(--theme-foreground)",
        muted: "var(--theme-muted)",
        subtle: "var(--theme-subtle)",
        border: "var(--theme-border)",
        "border-light": "var(--theme-border-light)",
        "dark-surface": "var(--theme-dark-surface)",
        "dark-deep": "var(--theme-dark-deep)",
        focus: "var(--theme-focus)",
        error: "var(--theme-error)",
        success: "var(--theme-success)",
        warning: "var(--theme-warning)",
        "on-error": "var(--theme-on-error)",
        "on-success": "var(--theme-on-success)",
        "on-warning": "var(--theme-on-warning)",
        "warm-silver": "var(--theme-warm-silver)",
        "charcoal-warm": "var(--theme-charcoal-warm)",
        "dark-warm": "var(--theme-dark-warm)",
        "ring-warm": "var(--theme-ring-warm)",
        "ring-deep": "var(--theme-ring-deep)",
      },
      fontFamily: {
        serif: [
          "Inter",
          "'Noto Sans SC'",
          "'Noto Sans CJK SC'",
          "system-ui",
          "sans-serif",
        ],
        sans: [
          "Inter",
          "'Noto Sans SC'",
          "system-ui",
          "'Noto Sans CJK SC'",
          "'Microsoft YaHei'",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "sans-serif",
        ],
        mono: [
          "'JetBrains Mono'",
          "ui-monospace",
          "SFMono-Regular",
          "'SF Mono'",
          "monospace",
        ],
      },
      lineHeight: {
        "heading-tight": "1.10",
        heading: "1.20",
        "heading-relaxed": "1.30",
        body: "1.60",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        "3xl": "32px",
      },
      boxShadow: {
        ring: "0 1px 2px color-mix(in srgb, var(--theme-shadow) 3%, transparent)",
        "ring-brand":
          "0 1px 2px color-mix(in srgb, var(--theme-shadow) 6%, transparent)",
        "ring-error": "0 0 0 1px var(--theme-error)",
        "ring-warning": "0 0 0 1px var(--theme-warning)",
        "ring-success": "0 0 0 1px var(--theme-success)",
        whisper:
          "0 8px 32px color-mix(in srgb, var(--theme-shadow) 6%, transparent)",
        inset: "inset 0 0 0 1px var(--theme-border)",
      },
      keyframes: {
        "slide-in-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out-right": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(100%)" },
        },
        "slide-in-left": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out-left": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-100%)" },
        },
        "toast-in": {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "toast-out": {
          from: { transform: "translateX(0)", opacity: "1" },
          to: { transform: "translateX(100%)", opacity: "0" },
        },
      },
      animation: {
        "slide-in-right": "slide-in-right 200ms ease-out",
        "slide-out-right": "slide-out-right 200ms ease-in",
        "slide-in-left": "slide-in-left 200ms ease-out",
        "slide-out-left": "slide-out-left 200ms ease-in",
        "toast-in": "toast-in 200ms ease-out",
        "toast-out": "toast-out 200ms ease-in",
      },
      typography: {
        DEFAULT: {
          css: {
            "--tw-prose-body": "var(--theme-foreground)",
            "--tw-prose-headings": "var(--theme-foreground)",
            "--tw-prose-lead": "var(--theme-muted)",
            "--tw-prose-links": "var(--theme-brand)",
            "--tw-prose-bold": "var(--theme-foreground)",
            "--tw-prose-counters": "var(--theme-muted)",
            "--tw-prose-bullets": "var(--theme-muted)",
            "--tw-prose-hr": "var(--theme-border)",
            "--tw-prose-quotes": "var(--theme-foreground)",
            "--tw-prose-quote-borders": "var(--theme-border)",
            "--tw-prose-captions": "var(--theme-muted)",
            "--tw-prose-kbd": "var(--theme-foreground)",
            "--tw-prose-code": "var(--theme-foreground)",
            "--tw-prose-pre-code": "var(--theme-foreground)",
            "--tw-prose-pre-bg": "var(--theme-surface-muted)",
            "--tw-prose-th-borders": "var(--theme-border)",
            "--tw-prose-td-borders": "var(--theme-border-light)",
            kbd: { boxShadow: "0 0 0 1px var(--theme-border)" },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
          },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
