/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx,html}"],
  theme: {
    extend: {
      colors: {
        canvas: "#ffffff",
        surface: "#ffffff",
        tint: "#edf5f0",
        "surface-muted": "#f6f8f7",
        brand: "#28644f",
        accent: "#20533f",
        foreground: "#203b30",
        muted: "#62726a",
        subtle: "#62726a",
        border: "#e0e7e2",
        "border-light": "#edf0ee",
        "dark-surface": "#26332d",
        "dark-deep": "#111b16",
        focus: "#337b5f",
        error: "#b53333",
        success: "#256b4d",
        warning: "#8a5900",
        "warm-silver": "#aebbb3",
        "charcoal-warm": "#4e6056",
        "dark-warm": "#34483d",
        "ring-warm": "#dce5df",
        "ring-deep": "#bacbc0",
      },
      fontFamily: {
        serif: [
          "Inter",
          "'Noto Sans SC'",
          "'Noto Sans CJK SC'",
          "system-ui",
          "sans-serif",
        ],
        sans: [
          "Inter",
          "'Noto Sans SC'",
          "system-ui",
          "'Noto Sans CJK SC'",
          "'Microsoft YaHei'",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "sans-serif",
        ],
        mono: [
          "'JetBrains Mono'",
          "ui-monospace",
          "SFMono-Regular",
          "'SF Mono'",
          "monospace",
        ],
      },
      lineHeight: {
        "heading-tight": "1.10",
        heading: "1.20",
        "heading-relaxed": "1.30",
        body: "1.60",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        "3xl": "32px",
      },
      boxShadow: {
        ring: "0 1px 2px rgb(24 47 36 / 0.03)",
        "ring-brand": "0 1px 2px rgb(24 47 36 / 0.06)",
        "ring-error": "0px 0px 0px 1px #b53333",
        "ring-warning": "0px 0px 0px 1px #8a5900",
        "ring-success": "0px 0px 0px 1px #256b4d",
        whisper: "0 8px 32px rgb(24 47 36 / 0.06)",
        inset: "inset 0px 0px 0px 1px rgba(0,0,0,0.15)",
      },
      keyframes: {
        "slide-in-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out-right": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(100%)" },
        },
        "slide-in-left": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out-left": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-100%)" },
        },
        "toast-in": {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "toast-out": {
          from: { transform: "translateX(0)", opacity: "1" },
          to: { transform: "translateX(100%)", opacity: "0" },
        },
      },
      animation: {
        "slide-in-right": "slide-in-right 200ms ease-out",
        "slide-out-right": "slide-out-right 200ms ease-in",
        "slide-in-left": "slide-in-left 200ms ease-out",
        "slide-out-left": "slide-out-left 200ms ease-in",
        "toast-in": "toast-in 200ms ease-out",
        "toast-out": "toast-out 200ms ease-in",
      },
      typography: {
        DEFAULT: {
          css: {
            "--tw-prose-links": "#28644f",
            "--tw-prose-code": "#203b30",
            "code::before": { content: '""' },
            "code::after": { content: '""' },
          },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
